hesai_lidar_node:
  ros__parameters:
    pcap_file: ""
    server_ip: "192.168.1.201"
    lidar_recv_port: 2368
    gps_port: 10110
    start_angle: 0
    lidar_type: "PandarQT"
    frame_id: "PandarQT"
    pcldata_type: 0
    publish_type: "points"
    timestamp_type: ""
    data_type: ""
    namespace: "hesai"
    lidar_correction_file: "../config/correction.csv"
